// UI chrome strings. These follow the chosen app locale (en/ru) — distinct from
// the per-question content locale (es/en/ru) handled by i18n.js. Spanish is a
// content language only, so UI chrome falls back to English.
import { getLanguageFromStorage } from "./language";

const STRINGS = {
    en: {
        chooseCategory: "Choose Your Test Category",
        question: "Question",
        check: "Check answer",
        chooseAnswer: "Choose an answer",
        next: "Next question",
        allLearned: "You've learned everything. Congrats!",
        reset: "Reset",
        questionsLabel: "questions",
        masteredLabel: "mastered",
        masteredNote: "questions answered correctly several times in a row",
        settings: "Settings",
        language: "Language:",
        selectLanguage: "Select language",
        testCategory: "Test category:",
        progress: "Progress:",
        export: "Export",
        import: "Import",
        importFailed: "Could not import: ",
        importSkipped: "Some entries in the backup were invalid and were skipped: ",
        disclaimer: "Unofficial practice tool — questions on the real exam may differ.",
        share: "Share",
        shareText: "Practice for the Buenos Aires driver's-license written exam:",
        linkCopied: "Link copied!",
        // mode chrome + exam/review screens
        practice: "Practice",
        mockExam: "Mock exam",
        review: "Review",
        reviewMistakes: "Review mistakes",
        category: "Category",
        home: "Home",
        loading: "Loading…",
        min: "min",
        passAt: "pass at",
        preparingExam: "Preparing exam…",
        passed: "Passed",
        notPassed: "Not passed",
        correctLabel: "correct",
        need: "need",
        timeExpired: "Time expired before you finished.",
        examPassMsg: "You'd likely pass the real exam. Keep practicing to stay sharp.",
        examFailMsg: "You may miss at most {n}. Review the misses below and keep practicing.",
        retakeExam: "Retake exam",
        noAnswer: "(no answer)",
        back: "Back",
        answered: "answered",
        finish: "Finish",
        nextShort: "Next",
        noMistakes: "No mistakes to review. 🎉",
        reviewComplete: "Review complete.",
        cleared: "Cleared {n} of {total}.",
    },
    ru: {
        chooseCategory: "Выберите категорию теста",
        question: "Вопрос",
        check: "Проверить ответ",
        chooseAnswer: "Выберите ответ",
        next: "Следующий вопрос",
        allLearned: "Ты всё выучил, поздравляю!",
        reset: "Сбросить",
        questionsLabel: "вопросов",
        masteredLabel: "выучено",
        masteredNote: "вопросы, на которые вы несколько раз подряд ответили правильно",
        settings: "Параметры",
        language: "Язык:",
        selectLanguage: "Выберите язык",
        testCategory: "Категория теста:",
        progress: "Прогресс:",
        export: "Экспорт",
        import: "Импорт",
        importFailed: "Не удалось импортировать: ",
        importSkipped: "Некоторые записи в файле некорректны и были пропущены: ",
        disclaimer: "Неофициальный тренажёр — вопросы на реальном экзамене могут отличаться.",
        share: "Поделиться",
        shareText: "Тренажёр для письменного экзамена на права в Буэнос-Айресе:",
        linkCopied: "Ссылка скопирована!",
        // mode chrome + exam/review screens
        practice: "Практика",
        mockExam: "Пробный экзамен",
        review: "Разбор",
        reviewMistakes: "Работа над ошибками",
        category: "Категория",
        home: "Главная",
        loading: "Загрузка…",
        min: "мин",
        passAt: "проходной",
        preparingExam: "Подготовка экзамена…",
        passed: "Сдано",
        notPassed: "Не сдано",
        correctLabel: "правильно",
        need: "нужно",
        timeExpired: "Время вышло, экзамен не завершён.",
        examPassMsg: "Скорее всего, вы сдадите настоящий экзамен. Продолжайте тренироваться, чтобы не растерять навык.",
        examFailMsg: "Можно ошибиться не более чем в {n}. Разберите ошибки ниже и продолжайте тренироваться.",
        retakeExam: "Пройти ещё раз",
        noAnswer: "(нет ответа)",
        back: "Назад",
        answered: "отвечено",
        finish: "Завершить",
        nextShort: "Далее",
        noMistakes: "Ошибок для разбора нет. 🎉",
        reviewComplete: "Разбор завершён.",
        cleared: "Разобрано {n} из {total}.",
    },
};

function getUiLocale() {
    return getLanguageFromStorage() === "ru" ? "ru" : "en";
}

function t(key) {
    const l = getUiLocale();
    return (STRINGS[l] && STRINGS[l][key]) || STRINGS.en[key] || key;
}

export { t, getUiLocale };
