// UI chrome strings. These follow the chosen app locale (es/en/ru) — distinct
// from the per-question content locale (es/en/ru) handled by i18n.js. Picking
// Spanish as the app locale also means questions show untranslated (es).
import { getLanguageFromStorage } from "./language";

const STRINGS = {
    es: {
        chooseCategory: "Elegí la categoría de tu examen",
        question: "Pregunta",
        check: "Verificar respuesta",
        chooseAnswer: "Elegí una respuesta",
        next: "Siguiente pregunta",
        allLearned: "¡Aprendiste todo. Felicitaciones!",
        reset: "Reiniciar",
        questionsLabel: "preguntas",
        masteredLabel: "dominadas",
        masteredNote: "preguntas respondidas correctamente varias veces seguidas",
        settings: "Configuración",
        language: "Idioma:",
        selectLanguage: "Elegí un idioma",
        testCategory: "Categoría del examen:",
        disclaimer: "El examen real puede diferir.",
        share: "Compartir",
        shareText: "Practicá para el examen teórico de la licencia de conducir de Buenos Aires:",
        linkCopied: "¡Enlace copiado!",
        // mode chrome + exam/review screens
        practice: "Práctica",
        mockExam: "Examen de práctica",
        review: "Repaso",
        reviewMistakes: "Repasar errores",
        category: "Categoría",
        home: "Inicio",
        loading: "Cargando…",
        min: "min",
        passAt: "se aprueba con",
        preparingExam: "Preparando el examen…",
        passed: "Aprobado",
        notPassed: "No aprobado",
        correctLabel: "correctas",
        need: "necesitás",
        timeExpired: "Se acabó el tiempo antes de terminar.",
        examPassMsg: "Probablemente aprobarías el examen real. Seguí practicando para no perder el nivel.",
        examFailMsg: "Podés equivocarte como máximo en {n}. Revisá los errores de abajo y seguí practicando.",
        retakeExam: "Rehacer examen",
        examInProgress: "Tenés un examen sin terminar.",
        continueExam: "Continuar",
        startOver: "Empezar de nuevo",
        noAnswer: "(sin respuesta)",
        back: "Atrás",
        answered: "respondidas",
        finish: "Finalizar",
        nextShort: "Siguiente",
        noMistakes: "No hay errores para repasar. 🎉",
        reviewComplete: "Repaso completado.",
        cleared: "Resueltos {n} de {total}.",
        // dashboard readiness status
        examReadiness: "Preparación para el examen",
        likelyToPass: "de probabilidad de aprobar ahora",
        masteredStat: "Dominadas",
        toGo: "restantes",
        seen: "vistas",
        recentLabel: "reciente",
        overallLabel: "general",
    },
    en: {
        chooseCategory: "Choose Your Test Category",
        question: "Question",
        check: "Check answer",
        chooseAnswer: "Choose an answer",
        next: "Next question",
        allLearned: "You've learned everything. Congrats!",
        reset: "Reset",
        questionsLabel: "questions",
        masteredLabel: "mastered",
        masteredNote: "questions answered correctly several times in a row",
        settings: "Settings",
        language: "Language:",
        selectLanguage: "Select language",
        testCategory: "Test category:",
        disclaimer: "Real exam may differ.",
        share: "Share",
        shareText: "Practice for the Buenos Aires driver's-license written exam:",
        linkCopied: "Link copied!",
        // mode chrome + exam/review screens
        practice: "Practice",
        mockExam: "Mock exam",
        review: "Review",
        reviewMistakes: "Review mistakes",
        category: "Category",
        home: "Home",
        loading: "Loading…",
        min: "min",
        passAt: "pass at",
        preparingExam: "Preparing exam…",
        passed: "Passed",
        notPassed: "Not passed",
        correctLabel: "correct",
        need: "need",
        timeExpired: "Time expired before you finished.",
        examPassMsg: "You'd likely pass the real exam. Keep practicing to stay sharp.",
        examFailMsg: "You may miss at most {n}. Review the misses below and keep practicing.",
        retakeExam: "Retake exam",
        examInProgress: "You have an unfinished exam.",
        continueExam: "Continue",
        startOver: "Start over",
        noAnswer: "(no answer)",
        back: "Back",
        answered: "answered",
        finish: "Finish",
        nextShort: "Next",
        noMistakes: "No mistakes to review. 🎉",
        reviewComplete: "Review complete.",
        cleared: "Cleared {n} of {total}.",
        // dashboard readiness status
        examReadiness: "Exam readiness",
        likelyToPass: "likely to pass right now",
        masteredStat: "Mastered",
        toGo: "to go",
        seen: "seen",
        recentLabel: "recent",
        overallLabel: "overall",
    },
    ru: {
        chooseCategory: "Выберите категорию теста",
        question: "Вопрос",
        check: "Проверить ответ",
        chooseAnswer: "Выберите ответ",
        next: "Следующий вопрос",
        allLearned: "Ты всё выучил, поздравляю!",
        reset: "Сбросить",
        questionsLabel: "вопросов",
        masteredLabel: "выучено",
        masteredNote: "вопросы, на которые вы несколько раз подряд ответили правильно",
        settings: "Параметры",
        language: "Язык:",
        selectLanguage: "Выберите язык",
        testCategory: "Категория теста:",
        disclaimer: "Реальный экзамен может отличаться.",
        share: "Поделиться",
        shareText: "Тренажёр для письменного экзамена на права в Буэнос-Айресе:",
        linkCopied: "Ссылка скопирована!",
        // mode chrome + exam/review screens
        practice: "Практика",
        mockExam: "Пробный экзамен",
        review: "Разбор",
        reviewMistakes: "Работа над ошибками",
        category: "Категория",
        home: "Главная",
        loading: "Загрузка…",
        min: "мин",
        passAt: "проходной",
        preparingExam: "Подготовка экзамена…",
        passed: "Сдано",
        notPassed: "Не сдано",
        correctLabel: "правильно",
        need: "нужно",
        timeExpired: "Время вышло, экзамен не завершён.",
        examPassMsg: "Скорее всего, вы сдадите настоящий экзамен. Продолжайте тренироваться, чтобы не растерять навык.",
        examFailMsg: "Можно ошибиться не более чем в {n}. Разберите ошибки ниже и продолжайте тренироваться.",
        retakeExam: "Пройти ещё раз",
        examInProgress: "У вас есть незавершённый экзамен.",
        continueExam: "Продолжить",
        startOver: "Начать заново",
        noAnswer: "(нет ответа)",
        back: "Назад",
        answered: "отвечено",
        finish: "Завершить",
        nextShort: "Далее",
        noMistakes: "Ошибок для разбора нет. 🎉",
        reviewComplete: "Разбор завершён.",
        cleared: "Разобрано {n} из {total}.",
        // dashboard readiness status
        examReadiness: "Готовность к экзамену",
        likelyToPass: "вероятность сдать прямо сейчас",
        masteredStat: "Выучено",
        toGo: "осталось",
        seen: "пройдено",
        recentLabel: "недавняя",
        overallLabel: "общая",
    },
};

function getUiLocale() {
    const lang = getLanguageFromStorage();
    return STRINGS[lang] ? lang : "en";
}

function t(key) {
    const l = getUiLocale();
    return (STRINGS[l] && STRINGS[l][key]) || STRINGS.en[key] || key;
}

export { t, getUiLocale };
